import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Stella Virginia
 */
public class frmIdentitasApotek extends javax.swing.JFrame {
    clsIdentitasApotek objIdentitasApotek = new clsIdentitasApotek();
    private TableColumn column;
    /**
     * Creates new form frmIdentitasApotek
     */
    public frmIdentitasApotek() {
        initComponents();
        
        //Untuk mematikan tombol close
        setDefaultCloseOperation(frmPengguna.DO_NOTHING_ON_CLOSE);
        //koneksi ke database
        objIdentitasApotek.AksesData(); //terhubung ke database
        IsiTabel(); //mengisi jTable dgn data
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNamaApotek = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNoTlp = new javax.swing.JTextField();
        txtPimpinan = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Nama Apotek");

        jLabel2.setText("Alamat  ");

        jLabel3.setText("No. Tlp   ");

        jLabel4.setText("Pimpinan  ");

        jLabel5.setText("Alamat Email ");

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("IDENTITAS APOTEK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        txtNamaApotek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaApotekActionPerformed(evt);
            }
        });
        txtNamaApotek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaApotekKeyPressed(evt);
            }
        });

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });

        txtNoTlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTlpActionPerformed(evt);
            }
        });
        txtNoTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoTlpKeyPressed(evt);
            }
        });

        txtPimpinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPimpinanActionPerformed(evt);
            }
        });
        txtPimpinan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPimpinanKeyPressed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabel);

        btnBaru.setText("New");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Exit");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaApotek)
                            .addComponent(txtAlamat)
                            .addComponent(txtNoTlp)
                            .addComponent(txtPimpinan)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNamaApotek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPimpinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBaru)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addGap(14, 14, 14)
                        .addComponent(btnKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     //Prosedur membersihkan isian data
    public void BersihIsian()
    {
       txtNamaApotek.setText("");
       txtNamaApotek.requestFocus();
       txtAlamat.setText("");
       txtNoTlp.setText("");
       txtPimpinan.setText("");
       txtEmail.setText("");
    }
    
    //Prosedur mengatur kolom jTable
    private void AturKolom() {
        jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = jTabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(160);
        column = jTabel.getColumnModel().getColumn(2);
        column.setPreferredWidth(160);
        column = jTabel.getColumnModel().getColumn(3);
        column.setPreferredWidth(160);
        column = jTabel.getColumnModel().getColumn(4);
        column.setPreferredWidth(160);
      
        
    }
    
    //Prosedur menampilkan data ke jTable
    private void IsiTabel() {
     DefaultTableModel tabelmapel = new DefaultTableModel();
     
     tabelmapel.addColumn("NamaApotek");
     tabelmapel.addColumn("Alamat");
     tabelmapel.addColumn("NoTlp");
     tabelmapel.addColumn("Pimpinan");
     tabelmapel.addColumn("AlamatEmail");
     
     try
     {
         objIdentitasApotek.AksesData();
         objIdentitasApotek.TampilData();
         Statement stat1 = objIdentitasApotek.conn.createStatement();
         ResultSet res1=stat1.executeQuery(objIdentitasApotek.sql);
         while (res1.next())
         {
             tabelmapel.addRow(new Object[]{res1.getString(1),res1.getString(2),res1.getString(3),res1.getString(4),res1.getString(5)});
         }
         jTabel.setModel(tabelmapel);
         AturKolom(); //atur kolom jTable
     }
     catch (Exception e)
     {
     }
         
    }
    
    //Prosedur simpan data
    private void SimpanData()
    {
        if(txtNamaApotek.getText().equals("")||txtNamaApotek.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Data harus diisi semua");
        }
        else
        {
            try
            {
                objIdentitasApotek.AksesData();
                objIdentitasApotek.NamaApotek = txtNamaApotek.getText();
                objIdentitasApotek.Alamat = txtAlamat.getText();
                objIdentitasApotek.NoTlp = txtNoTlp.getText();
                objIdentitasApotek.Pimpinan = txtPimpinan.getText();
                objIdentitasApotek.AlamatEmail = txtEmail.getText();
                objIdentitasApotek.Simpan();
                objIdentitasApotek.res.executeUpdate(objIdentitasApotek.sql);
                objIdentitasApotek.conn.close();
                BersihIsian();
                IsiTabel();
                txtNamaApotek.requestFocus();
                JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
            }
            catch (Exception e)
            {
              JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal");
              System.out.println(e.getMessage());
            }
        }
    }
    
    
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getHeight())/2;
        this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void txtNamaApotekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaApotekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaApotekActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtNoTlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTlpActionPerformed

    private void txtPimpinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPimpinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPimpinanActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNamaApotekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaApotekKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            if ((txtNamaApotek.getText().length() < 1) || (txtNamaApotek.getText().isEmpty()))
                  {
                     JOptionPane.showMessageDialog(this, "Panjang ID harus 8 digit","Informasi",
                     JOptionPane.INFORMATION_MESSAGE);
                     txtNamaApotek.requestFocus();
                  }
            else
            {
               txtAlamat.requestFocus(); 
            }
        }
    }//GEN-LAST:event_txtNamaApotekKeyPressed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
           if (txtAlamat.getText().isEmpty())
           {
               JOptionPane.showMessageDialog(this, "Nama masih kosong","Informasi",
               JOptionPane.INFORMATION_MESSAGE);
               txtAlamat.requestFocus();
           }
           else
           {
              txtNoTlp.requestFocus(); 
           }
        }
    }//GEN-LAST:event_txtAlamatKeyPressed

    private void txtNoTlpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTlpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            if (txtNoTlp.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Password masih kosong","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                txtNoTlp.requestFocus();
            }
            else
            {
                txtPimpinan.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNoTlpKeyPressed

    private void txtPimpinanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPimpinanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            if (txtPimpinan.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Alamat masih kosong","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                txtPimpinan.requestFocus();
            }
            else
            {
                txtEmail.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPimpinanKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            if (txtEmail.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Alamat masih kosong","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
                txtEmail.requestFocus();
            }
            else
            {
                btnSimpan.requestFocus();
            }
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        try
        {
           BersihIsian();
           IsiTabel();
           txtNamaApotek.requestFocus();
        }
       catch (Exception e)
       {
       }
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
         SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
         SimpanData();
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtNamaApotek.getText().equals("")||txtNamaApotek.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Masukkan ID Pengguna");
        }
        else
        {
            try
            {
               objIdentitasApotek.AksesData();
               objIdentitasApotek.NamaApotek = txtNamaApotek.getText();
               objIdentitasApotek.Alamat = txtAlamat.getText();
               objIdentitasApotek.NoTlp = txtNoTlp.getText();
               objIdentitasApotek.Pimpinan = txtPimpinan.getText();
               objIdentitasApotek.AlamatEmail = txtEmail.getText();
               
               objIdentitasApotek.Edit();
               objIdentitasApotek.res.executeUpdate(objIdentitasApotek.sql);
               objIdentitasApotek.conn.close();
               BersihIsian();
               IsiTabel();
               JOptionPane.showMessageDialog(null,"Data berhasil diupdate");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/ koneksi gagal");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try
        {
          objIdentitasApotek.AksesData();
          objIdentitasApotek.NamaApotek = txtNamaApotek.getText();
          objIdentitasApotek.Hapus();
          objIdentitasApotek.res.executeUpdate(objIdentitasApotek.sql);
          objIdentitasApotek.conn.close();
          IsiTabel();
          BersihIsian();
          JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Proses penghapusan gagal/koneksi gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try
        {
            objIdentitasApotek.Keluar();
            dispose();
        }
        catch (Exception e){
            {
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void jTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelMouseClicked
        // TODO add your handling code here:
        int baris = jTabel.getSelectedRow();
        
        String kolom1 = jTabel.getValueAt(baris, 0).toString();
        String kolom2 = jTabel.getValueAt(baris, 1).toString();
        String kolom3 = jTabel.getValueAt(baris, 2).toString();
        String kolom4 = jTabel.getValueAt(baris, 3).toString();
        String kolom5 = jTabel.getValueAt(baris, 4).toString();
       
        
        txtNamaApotek.setText(kolom1);
        txtAlamat.setText(kolom2);
        txtNoTlp.setText(kolom3);
        txtPimpinan.setText(kolom4);
        txtEmail.setText(kolom5);
    }//GEN-LAST:event_jTabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIdentitasApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIdentitasApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIdentitasApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIdentitasApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIdentitasApotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaApotek;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JTextField txtPimpinan;
    // End of variables declaration//GEN-END:variables
}
