import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Stella Virginia
 */
public class frmStockObat extends javax.swing.JFrame {
    clsStockObat objStockObat = new clsStockObat();
    private TableColumn column;
    /**
     * Creates new form frmStockObat
     */
    public frmStockObat() {
        initComponents();
        objStockObat.AksesData();
        IsiTabel();
        IsiTabelFilter();
        IsiGrandTotalJual();
        IsiGrandTotalBeli();
        
        
         //Untuk mematikan tombol close
        setDefaultCloseOperation(frmPengguna.DO_NOTHING_ON_CLOSE);
        //koneksi ke database
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeAwal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHargaJual = new javax.swing.JTextField();
        txtTotalHargaBeli = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtKodeAkhir = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("FORM STOCK OBAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(480, 480, 480))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setText("Kode Awal : ");

        jLabel3.setText("Kode Akhir : ");

        txtKodeAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeAwalActionPerformed(evt);
            }
        });
        txtKodeAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeAwalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeAwalKeyReleased(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabel);

        jLabel4.setText("Total Harga Jual");

        jLabel5.setText("Total Harga Beli");

        txtTotalHargaJual.setEnabled(false);

        txtTotalHargaBeli.setEnabled(false);
        txtTotalHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaBeliActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnKeluar.setText("Exit");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtKodeAkhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeAkhirKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(21, 21, 21)
                                .addComponent(txtKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtKodeAkhir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(958, 958, 958)
                                .addComponent(btnClear)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(784, 784, 784)
                                        .addComponent(txtTotalHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(785, 785, 785)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTotalHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKodeAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnKeluar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try
        {
            objStockObat.Keluar();
            dispose();
        }
        catch (Exception e){
            {
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtKodeAwalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeAwalKeyReleased
        // TODO add your handling code here:
        IsiTabelFilter();
        IsiGrandTotalBeli();
        IsiGrandTotalJual();
    }//GEN-LAST:event_txtKodeAwalKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtKodeAwal.setText("");
        txtKodeAkhir.setText("");
        txtTotalHargaJual.setText("");
        txtTotalHargaBeli.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtKodeAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeAwalActionPerformed

    private void txtKodeAwalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeAwalKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
                txtKodeAkhir.requestFocus();
        }
        
    }//GEN-LAST:event_txtKodeAwalKeyPressed

    private void txtTotalHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaBeliActionPerformed

    private void txtKodeAkhirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeAkhirKeyReleased
        // TODO add your handling code here:
        IsiTabelFilter();
        IsiGrandTotalBeli();
        IsiGrandTotalJual();
    }//GEN-LAST:event_txtKodeAkhirKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getHeight())/2;
        this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

     private void IsiTabel() {
    DefaultTableModel tabelmapel = new DefaultTableModel();
 
 
    tabelmapel.addColumn("KodeObat");
    tabelmapel.addColumn("NamaObat");
    tabelmapel.addColumn("KodeKategori");
    tabelmapel.addColumn("KategoriObat"); 
    tabelmapel.addColumn("TanggalKadaluarsa"); 
    tabelmapel.addColumn("Keterangan"); 
    tabelmapel.addColumn("HargaBeli");
    tabelmapel.addColumn("HargaJual");
    tabelmapel.addColumn("Quantity");
    tabelmapel.addColumn("TotalHargaJual");
    tabelmapel.addColumn("TotalHargaBeli");
    try
    {
    objStockObat.AksesData();
    objStockObat.ShowStock();
 
    Statement stat1 = objStockObat.conn.createStatement();
    ResultSet res1=stat1.executeQuery(objStockObat.sql);
 
    while (res1.next())
 
    {
    tabelmapel.addRow(new
    Object[]{res1.getString(1),res1.getString(2),res1.getString(3),res1.getString(4),res1.getString(5),res1.getString(6),res1.getString(7), res1.getString(8), res1.getString(9), res1.getString(10), res1.getString(11)});
    }
 
    jTabel.setModel(tabelmapel);
    AturKolom(); //atur kolom jTable
    IsiGrandTotalBeli();
    IsiGrandTotalJual();
    }
 
 
    catch (Exception e)
    {
    }
    }
    
     public void IsiTabelFilter(){
        if(txtKodeAwal.getText().equals("") && txtKodeAkhir.getText().equals("") ){
             IsiTabel();
        }else{
               DefaultTableModel tabelmapel = new DefaultTableModel();
 
 
                tabelmapel.addColumn("KodeObat");
                tabelmapel.addColumn("NamaObat");
                tabelmapel.addColumn("KodeKategori");
                tabelmapel.addColumn("KategoriObat"); 
                tabelmapel.addColumn("TanggalKadaluarsa"); 
                tabelmapel.addColumn("Keterangan"); 
                tabelmapel.addColumn("HargaBeli");
                tabelmapel.addColumn("HargaJual");
                tabelmapel.addColumn("Quantity");
                tabelmapel.addColumn("TotalHargaJual");
                tabelmapel.addColumn("TotalHargaBeli");
 
             try
            {
                objStockObat.KodeAwal = txtKodeAwal.getText();
                objStockObat.KodeAkhir = txtKodeAkhir.getText();
                objStockObat.AksesData();
                objStockObat.TampilFilter(objStockObat.KodeAwal, objStockObat.KodeAkhir);
 
                 Statement stat1 = objStockObat.conn.createStatement();
                 ResultSet res1=stat1.executeQuery(objStockObat.sql);
 
             while (res1.next())
 
             {
              tabelmapel.addRow(new
              Object[]{res1.getString(1),res1.getString(2),res1.getString(3),res1.getString(4),res1.getString(5),res1.getString(6),res1.getString(7), res1.getString(8), res1.getString(9), res1.getString(10), res1.getString(11)});
             }
 
            jTabel.setModel(tabelmapel);
            AturKolom(); //atur kolom jTable
            IsiGrandTotalBeli();
            IsiGrandTotalJual();
    }
 
 
    catch (Exception e)
        {
        }
        }
 
    }
    
     public void IsiGrandTotalBeli(){
        int numrow = jTabel.getRowCount();
        double tot = 0;
        for (int i= 0; i<numrow; i++){
            double val = Double.valueOf(jTabel.getValueAt(i, 10).toString());
            tot += val;
 
            txtTotalHargaBeli.setText(Double.toString(tot));
        }
    }
     
     public void IsiGrandTotalJual(){
        int numrow = jTabel.getRowCount();
        double tot = 0;
        for (int i= 0; i<numrow; i++){
            double val = Double.valueOf(jTabel.getValueAt(i, 9).toString());
            tot += val;
 
            txtTotalHargaJual.setText(Double.toString(tot));
        }
    }
     
     private void AturKolom() {
        jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
 
        column = jTabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = jTabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(120);
        column = jTabel.getColumnModel().getColumn(2);
        column.setPreferredWidth(50);
        column = jTabel.getColumnModel().getColumn(3);
        column.setPreferredWidth(170);
        column = jTabel.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(5);
        column.setPreferredWidth(150);
        column = jTabel.getColumnModel().getColumn(6);
        column.setPreferredWidth(100); 
        column = jTabel.getColumnModel().getColumn(7);
        column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(8);
        column.setPreferredWidth(70);
        column = jTabel.getColumnModel().getColumn(9);
        column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(10);
        column.setPreferredWidth(100);
 
        }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStockObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStockObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStockObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStockObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStockObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtKodeAkhir;
    private javax.swing.JTextField txtKodeAwal;
    private javax.swing.JTextField txtTotalHargaBeli;
    private javax.swing.JTextField txtTotalHargaJual;
    // End of variables declaration//GEN-END:variables
}
